# Generated by Django 5.2 on 2025-04-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_deals_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='last_checked',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
