# Generated by Django 5.2 on 2025-05-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_alerthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerthistory',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
