# Generated by Django 5.2 on 2025-05-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_alerthistory_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerthistory',
            options={'ordering': ['time_sent']},
        ),
        migrations.AlterField(
            model_name='deals',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
