# Generated by Django 5.2 on 2025-06-06 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_alter_alerthistory_options_alter_deals_last_checked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerthistory',
            options={'ordering': ['-time_sent']},
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_history', to='deals.deals')),
            ],
            options={
                'verbose_name_plural': 'Prices History',
            },
        ),
    ]
