# Generated by Django 5.2 on 2025-06-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_alter_alerthistory_options_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
