# Generated by Django 5.2 on 2025-06-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_deals_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
