# Generated by Django 5.2 on 2025-06-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0014_alter_deals_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alerts_delete',
            field=models.BooleanField(default=True),
        ),
    ]
