# Generated by Django 5.2 on 2025-06-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0015_profile_alerts_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='image_path',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='deals',
            name='price_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='deals',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
