# Generated by Django 5.2 on 2025-06-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0017_deals_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='previous_price_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
