# Generated by Django 5.2 on 2025-07-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0019_scrapefailure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deals',
            options={'verbose_name_plural': 'Deals'},
        ),
        migrations.AddField(
            model_name='deals',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
