# Generated by Django 5.2 on 2025-07-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0020_alter_deals_options_deals_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='deformed',
            field=models.BooleanField(default=False),
        ),
    ]
